#!/usr/bin/env node


//file system to copy/paste or list files 
//create files delete files
const fs = require("fs");

//get argument from terminal
let templateName = process.argv[2];

if(templateName == "--list")
{
    let list = fs.readdirSync(__dirname+"/templates/");
    console.log("available=>", list.join(", "));
    process.exit(0);
}

if (!templateName) {
  console.error("\x1b[31mPlease enter template name");
  process.exit(0);
}
let source = __dirname + "/templates/" + templateName;

if (!fs.existsSync(source)) {
  console.error("\x1b[31mUnkown template "+templateName);
  process.exit(0);
}

//get the path where the command is called
let destination = process.cwd();

try {
  fs.cpSync(source, destination, {
    recursive: true,
  });
} catch (error) {
  console.log(error.message);
}
